# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tissue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('tarif', models.DecimalField(decimal_places=2, default=2.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='TissueCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menages.TissueCategory')),
            ],
            options={
                'ordering': ['tree_id', 'lft'],
            },
        ),
        migrations.AddField(
            model_name='tissue',
            name='tissuecategory',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menages.TissueCategory', verbose_name='Catégories'),
        ),
    ]
