# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menages', '0002_auto_20170616_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menages.WorkCategory')),
            ],
            options={
                'verbose_name': 'Type de travail',
                'ordering': ['tree_id', 'lft'],
            },
        ),
        migrations.AlterModelOptions(
            name='tissuecategory',
            options={'ordering': ['tree_id', 'lft'], 'verbose_name': 'Catégorie'},
        ),
    ]
