# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_amount', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Travail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('temps', models.DecimalField(decimal_places=2, help_text='1.5 = 1h30, 1.25: 1h15', max_digits=3)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
