# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conciergerie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travail',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
