# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciergerie', '0002_auto_20170706_0639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travail',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='travail',
            name='date',
            field=models.DateField(),
        ),
    ]
