# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 12:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conciergerie', '0003_auto_20170707_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='travail',
            name='owner',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
